### ISSUE TITLE
Can anyone please tell what this error is .I got this error when i was running npm run server

### ISSUE THREAD

**Issue by namrqthakaipa** [siddharthkp/cost-of-modules#60]
Error: Cannot parse config file: 'C:\DEVCONNECTOR\config\default.json': SyntaxError: Unexpected end of JSON input
    at Config.util.parseFile (C:\DEVCONNECTOR\node_modules\config\lib\config.js:794:11)
    at C:\DEVCONNECTOR\node_modules\config\lib\config.js:601:26
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (C:\DEVCONNECTOR\node_modules\config\lib\config.js:600:16)
    at new Config (C:\DEVCONNECTOR\node_modules\config\lib\config.js:116:27)
    at Object.<anonymous> (C:\DEVCONNECTOR\node_modules\config\lib\config.js:1441:31)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\DEVCONNECTOR\config\db.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by siddharthkp** [comment]
Looks like the json file - config/default.json isn't valid. Try putting it in https://jsonlint.com/ to see if there are any problems
